// TODO:
export const columns = [
  { name: "NAME", uid: "name" },
  { name: "ROLE", uid: "role" },
  { name: "STATUS", uid: "status" },
  { name: "ACTIONS", uid: "actions" },
];
export const users = [
  {
    id: 1,
    name: "T0m Jerry",
    role: "CEO",
    team: "Management",
    status: "active",
    age: "29",
  },
  {
    id: 2,
    name: "Snake Ali",
    role: "Technical Lead",
    team: "Development",
    status: "paused",
    age: "25",
  },
  {
    id: 3,
    name: "Tuna Blue",
    role: "Senior Developer",
    team: "Development",
    status: "active",
    age: "22",
  },
  {
    id: 4,
    name: "Halson Deep",
    role: "Community Manager",
    team: "Marketing",
    status: "vacation",
    age: "28",
  },
  {
    id: 5,
    name: "Muller Jhon",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
    age: "24",
  },
  {
    id: 6,
    name: "Sccopy Cena",
    role: "CEO",
    team: "Management",
    status: "active",
    age: "29",
  },
  {
    id: 10,
    name: "Cooper Zing",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
    age: "24",
  },
  {
    id: 8,
    name: "James Huna",
    role: "Senior Developer",
    team: "Development",
    status: "active",
    age: "22",
  },
  {
    id: 7,
    name: "Likewise St",
    role: "Technical Lead",
    team: "Development",
    status: "paused",
    age: "25",
  },

  {
    id: 9,
    name: "William Beok",
    role: "Community Manager",
    team: "Marketing",
    status: "vacation",
    age: "28",
  },
  {
    id: 11,
    name: "Jezz Ride",
    role: "CEO",
    team: "Management",
    status: "active",
    age: "29",
  },
  {
    id: 12,
    name: "Rizzler Sam",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
    age: "24",
  },
  {
    id: 13,
    name: "Touch james",
    role: "Senior Developer",
    team: "Development",
    status: "active",
    age: "22",
  },
  {
    id: 14,
    name: "Hungry Dad da les",
    role: "Technical Lead",
    team: "Development",
    status: "paused",
    age: "25",
  },
  {
    id: 15,
    name: "Fannades Cli",
    role: "CEO",
    team: "Management",
    status: "active",
    age: "29",
  },
  {
    id: 16,
    name: "Cal jocson",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
    age: "24",
  },
];
